# Generated by Django 2.2.4 on 2019-08-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=40, verbose_name='Nome do professor')),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Manhã', max_length=5, verbose_name='Turno')),
                ('horario', models.CharField(max_length=20, verbose_name='Horário')),
                ('dia', models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta')], default='Segunda', max_length=20, verbose_name='Dia disponível')),
                ('aluno', models.CharField(default='1', max_length=20)),
            ],
        ),
    ]
