# Generated by Django 2.2.4 on 2019-08-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0002_auto_20190830_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
