# Generated by Django 2.2.4 on 2019-08-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0003_auto_20190830_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lazer.Aluno'),
        ),
    ]
