# Generated by Django 2.2.4 on 2019-08-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0004_auto_20190830_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esportes_disponiveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esportes_disponiveis', models.CharField(choices=[('Futebol', 'Futebol'), ('Futsal', 'Futsal'), ('Natação', 'Natação'), ('Vôlei', 'Vôlei'), ('Badminton', 'Badminton'), ('Basquete', 'Basquete')], max_length=20)),
            ],
        ),
    ]
