# Generated by Django 2.2.2 on 2019-09-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0007_auto_20190902_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='esporte',
            field=models.CharField(choices=[('Futsal', 'Futsal'), ('Natação', 'Natação'), ('Badminton', 'Badminton'), ('Vôlei', 'Vôlei'), ('Basquete', 'Basquete'), ('Futebol', 'Futebol')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
