# Generated by Django 2.2.2 on 2019-09-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0008_reserva_esporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='esporte',
            field=models.CharField(blank=True, choices=[('Futsal', 'Futsal'), ('Natação', 'Natação'), ('Badminton', 'Badminton'), ('Vôlei', 'Vôlei'), ('Basquete', 'Basquete'), ('Futebol', 'Futebol')], max_length=20, null=True),
        ),
    ]
