# Generated by Django 2.2.2 on 2019-09-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0009_auto_20190902_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='esporte',
        ),
    ]
