# Generated by Django 2.2.2 on 2019-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0010_remove_reserva_esporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='esporte',
            field=models.CharField(blank=True, choices=[('Futsal', 'Futsal'), ('Futebol', 'Futebol'), ('Vôlei', 'Vôlei'), ('Badminton', 'Badminton'), ('Basquete', 'Basquete'), ('Natação', 'Natação')], max_length=20, null=True),
        ),
    ]
