# Generated by Django 2.2.2 on 2019-09-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0011_reserva_esporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='esporte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
