# Generated by Django 2.2.2 on 2019-09-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0012_auto_20190903_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='esporte',
            field=models.CharField(blank=True, choices=[('Futebol', 'Futebol'), ('Futsal', 'Futsal'), ('Vôlei', 'Vôlei'), ('Basquete', 'Basquete'), ('Badminton', 'Badminton'), ('Natação', 'Natação')], default='Futebol', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_professor',
            field=models.CharField(choices=[('Ari Oliveira', 'Ari Oliveira'), ('Mariana', 'Mariana'), ('Romerito', 'Romerito'), ('Hudson', 'Hudson')], default='Romerito', max_length=40, verbose_name='Nome do professor'),
        ),
    ]
