# Generated by Django 2.2.2 on 2019-09-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0013_auto_20190904_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='esporte',
            field=models.CharField(blank=True, choices=[('Futebol', 'Futebol'), ('Futsal', 'Futsal'), ('Vôlei', 'Vôlei'), ('Basquete', 'Basquete'), ('Badminton', 'Badminton'), ('Natação', 'Natação')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], default='Matutino', max_length=9, null=True, verbose_name='Turno')),
                ('aluno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lazer.Reserva')),
            ],
        ),
    ]
