# Generated by Django 2.2.2 on 2019-09-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0014_auto_20190908_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lazer.Reserva'),
        ),
    ]
