# Generated by Django 2.2.2 on 2019-09-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0015_auto_20190908_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='aluno',
        ),
    ]
