# Generated by Django 2.2.2 on 2019-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazer', '0016_remove_alunos_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], default='Matutino', max_length=9, verbose_name='Turno'),
        ),
    ]
